const dictionaries={
  en:{
    appTitle:'Room Monster Battle',skip:'Skip to game',online:'Online',offline:'Offline',parent:'Parent',loading:'Waking the room monster…',toggleSound:'Toggle sound',language:'Language',english:'English',spanish:'Español',
    setupTitle:'Grown-Up Setup',setupIntro:'First, choose two hero names. You can change them later.',hero1:'Hero 1 name',hero2:'Hero 2 name',next:'Next →',pinTitle:'Create Parent PIN',pinIntro:'Use four digits. The PIN itself is never stored.',pin4:'4-digit PIN',confirmPin:'Confirm PIN',preview:'Preview Setup →',pinMismatch:'PINs must match and contain four digits.',ready:'Ready for Battle',setupSummary:'Normal Battle will be the default. Sound and spoken instructions start enabled; parent inspection is on.',saveSetup:'Save Family Setup',
    monsterActive:'The monster is losing its mess!',monsterIdle:'A silly monster scrambled the room!',battleProgress:'Battle in progress!',heroesNeed:'Heroes, your room needs you!',progressSafe:'Your progress is safe. Jump back into the current mission.',homeStory:'Work together, rescue each room zone, and turn the monster into a friend.',resume:'Resume Battle',start:'Start Battle',hero:'Hero',
    chooseBattle:'Choose your battle',chooseBattleHelp:'Pick how much room rescuing your team wants to do.',briefing:'Battle briefing!',briefingText:'{mode} has {count} missions. The silly monster mixed up these room zones.',teamRule:'Work together. Each hero confirms their own part. Unsure or unsafe objects always go to a grown-up.',beginMission:'Begin Mission 1',
    role:'Role',done:'✓ Done',didPart:'I did my part!',teamContinue:'Team Check ✓ Continue',waitBoth:'Every assigned hero finishes their part before the team moves on.',missionCount:'Mission {current} of {total} • {time}',health:'{count} monster health remaining',safety:'Safety check: ',hear:'🔊 Hear Mission',help:'🙋 Need Help',moreTime:'⏱ More Time',pause:'⏸ Pause',helpNotice:'Put unsure items in the Ask a Grown-Up basket.',timeNotice:'You have all the time you need.',undoNotice:'Confirmation undone.',spokenUnavailable:'Spoken instructions are unavailable. Read the mission on screen.',
    zoneRescued:'Room zone rescued!',missionComplete:'{mission} is complete. The monster dropped a collectible!',nextMission:'Next Mission →',
    greatTeamwork:'Great teamwork!',inspectionAsk:'The room monster is tired. Ask a grown-up for the final room check.',grownInspection:'Grown-Up Inspection',parentInspection:'Parent Inspection',inspectionHelp:'Approve the room, or return only the missions that need another pass. Prior child credit stays recorded.',returnLook:'Return {mission} for one more look',optionalNote:'Optional friendly note',note:'Note',approveRoom:'Approve Room',returnSelected:'Return Selected',selectMission:'Select at least one mission.',
    victory:'Victory! The monster is your friend!',victoryText:'You rescued the room by working as a team.',finishBattle:'Finish Battle',battleSaved:'Battle saved. Great teamwork!',
    paused:'Battle paused',pauseText:'Take a water or movement break. Nothing is lost.',resumeBattle:'Resume Battle',parentPin:'Parent PIN',grownArea:'Grown-up area',pinWrong:'PIN did not match.',locked:'Locked for {seconds} seconds.',parentClosed:'Parent mode closed after inactivity.',timerHidden:'Timer ignored time while the app was hidden.',offlineUnavailable:'Offline install is unavailable in this browser.',updateAfter:'Update ready after this battle.',updateReady:'Update ready. Reload when convenient.',restartTitle:'Room Monster Battle needs a restart',restartText:'Local storage could not be opened. Try reloading Safari.',
    nav_dashboard:'Dashboard',nav_profiles:'Profiles',nav_missions:'Missions',nav_modes:'Modes',nav_rewards:'Rewards',nav_settings:'Settings',nav_history:'History',nav_data:'Data',parentSection:'Parent: {section}',summary:'{heroes} active heroes • {missions} active missions • {sessions} saved sessions',autoClose:'Parent mode closes automatically after five minutes of inactivity.',returnChild:'Return to Child Mode',active:'Active',save:'Save',profileSaved:'Profile saved.',addHero:'Add Hero',removeHero:'Remove',participantLimit:'Up to {count} heroes can join a battle.',heroName:'Hero name',timerLabel:'Mission timer',timerReset:'New chance! 5:00',timerExpired:'It looks like you missed the first chance, but the monster is distracted now. You can still make it — try again!',timerExpiredAgain:'The monster is still distracted! You have another five minutes. Keep going!',missionAlarm:'Important mission starting!',moreHeroes:'Add another hero',newHero:'New Hero',roomRanger:'Room Ranger',duplicate:'Duplicate',copySuffix:' Copy',missionUpdated:'Mission updated.',restoreFactory:'Restore Factory Missions',restoreConfirm:'Restore the original eight missions? Custom missions stay.',familyReward:'Family reward message',saveReward:'Save Reward Message',rewardSaved:'Reward message saved.',spokenSetting:'Spoken mission instructions',inspectSetting:'Require final parent inspection',reduceMotion:'Reduce animation',interfaceLanguage:'Interface language',saveSettings:'Save Settings',settingsSaved:'Settings saved.',noBattles:'No completed battles yet.',battle:'Battle',missionsWord:'missions',inspected:'Inspected',completed:'Completed',exportBackup:'Export JSON Backup',importBackup:'Import backup',validateImport:'Validate & Import',resetWarning:'Full reset deletes local family data from this browser.',fullReset:'Full Reset…',chooseBackup:'Choose a JSON backup first.',validBackup:'Valid backup: {heroes} heroes, {missions} missions, {sessions} sessions. Replace current local data?',backupImported:'Backup imported.',importRejected:'Import rejected: {message}',reset1:'First confirmation: delete all local Room Monster Battle data?',reset2:'Second confirmation: this cannot be undone without a backup. Continue?',resetPhrase:'Type RESET ROOM MONSTER to finish:',resetCancelled:'Reset cancelled.',
    quick:'Quick Rescue',normal:'Normal Battle',deep:'Deep Clean',finder:'Finder',sorter:'Sorter',organizer:'Organizer',trashScout:'Trash Scout',toyCaptain:'Toy Captain',bedBuilder:'Bed Builder',finalInspector:'Final Inspector',closet:'Closet',bookshelf:'Book Shelf',floor:'Floor',toyZone:'Toy Zone',beds:'Beds',wholeRoom:'Whole Room'
  },
  es:{
    appTitle:'Batalla contra el Monstruo del Cuarto',skip:'Saltar al juego',online:'En línea',offline:'Sin conexión',parent:'Padres',loading:'Despertando al monstruo del cuarto…',toggleSound:'Activar o silenciar sonido',language:'Idioma',english:'English',spanish:'Español',
    setupTitle:'Configuración para padres',setupIntro:'Primero, elige por lo menos dos héroes. Puedes agregar más participantes ahora o después.',hero1:'Nombre del héroe 1',hero2:'Nombre del héroe 2',next:'Siguiente →',pinTitle:'Crear PIN para padres',pinIntro:'Usa cuatro dígitos. El PIN nunca se guarda directamente.',pin4:'PIN de 4 dígitos',confirmPin:'Confirmar PIN',preview:'Vista previa →',pinMismatch:'Los PIN deben coincidir y tener cuatro dígitos.',ready:'¡Listos para la batalla!',setupSummary:'Batalla Normal será el modo predeterminado. El sonido, las instrucciones habladas, la cuenta regresiva de cinco minutos y la inspección de padres estarán activados.',saveSetup:'Guardar configuración familiar',
    monsterActive:'¡El monstruo está perdiendo su desorden!',monsterIdle:'¡Un monstruo travieso desordenó el cuarto!',battleProgress:'¡Batalla en progreso!',heroesNeed:'¡Héroes, su cuarto los necesita!',progressSafe:'Su progreso está guardado. Regresen a la misión actual.',homeStory:'Trabajen en equipo, rescaten cada zona del cuarto y conviertan al monstruo en amigo.',resume:'Continuar batalla',start:'Comenzar batalla',hero:'Héroe',
    chooseBattle:'Elige tu batalla',chooseBattleHelp:'Elige cuánto del cuarto quiere rescatar tu equipo.',briefing:'¡Informe de batalla!',briefingText:'{mode} tiene {count} misiones. El monstruo travieso revolvió estas zonas del cuarto.',teamRule:'Trabajen juntos. Cada héroe confirma su propia parte. Los objetos dudosos o peligrosos siempre se llevan a un adulto.',beginMission:'Comenzar misión 1',
    role:'Rol',done:'✓ Listo',didPart:'¡Hice mi parte!',teamContinue:'Revisión del equipo ✓ Continuar',waitBoth:'Cada héroe asignado termina su parte antes de que el equipo continúe.',missionCount:'Misión {current} de {total} • {time}',health:'Quedan {count} puntos de salud del monstruo',safety:'Seguridad: ',hear:'🔊 Escuchar misión',help:'🙋 Necesito ayuda',moreTime:'⏱ Más tiempo',pause:'⏸ Pausa',helpNotice:'Coloca los objetos dudosos en la canasta “Pregúntale a un adulto”.',timeNotice:'Tienen todo el tiempo que necesiten.',undoNotice:'Confirmación deshecha.',spokenUnavailable:'Las instrucciones habladas no están disponibles. Lee la misión en pantalla.',
    zoneRescued:'¡Zona del cuarto rescatada!',missionComplete:'{mission} está completa. ¡El monstruo dejó caer un coleccionable!',nextMission:'Siguiente misión →',
    greatTeamwork:'¡Excelente trabajo en equipo!',inspectionAsk:'El monstruo del cuarto está cansado. Pídanle a un adulto la revisión final.',grownInspection:'Inspección de un adulto',parentInspection:'Inspección de padres',inspectionHelp:'Aprueba el cuarto o devuelve solamente las misiones que necesiten otra revisión. El crédito previo de los niños se conserva.',returnLook:'Revisar {mission} una vez más',optionalNote:'Nota amistosa opcional',note:'Nota',approveRoom:'Aprobar cuarto',returnSelected:'Devolver seleccionadas',selectMission:'Selecciona por lo menos una misión.',
    victory:'¡Victoria! ¡El monstruo es su amigo!',victoryText:'Rescataron el cuarto trabajando en equipo.',finishBattle:'Terminar batalla',battleSaved:'Batalla guardada. ¡Excelente trabajo en equipo!',
    paused:'Batalla en pausa',pauseText:'Tomen agua o muévanse un poco. No se pierde nada.',resumeBattle:'Continuar batalla',parentPin:'PIN para padres',grownArea:'Área para adultos',pinWrong:'El PIN no coincide.',locked:'Bloqueado por {seconds} segundos.',parentClosed:'El modo para padres se cerró por inactividad.',timerHidden:'El temporizador ignoró el tiempo mientras la aplicación estuvo oculta.',offlineUnavailable:'La instalación sin conexión no está disponible en este navegador.',updateAfter:'Hay una actualización lista para después de esta batalla.',updateReady:'Hay una actualización lista. Recarga cuando sea conveniente.',restartTitle:'Batalla contra el Monstruo del Cuarto necesita reiniciarse',restartText:'No se pudo abrir el almacenamiento local. Intenta recargar Safari.',
    nav_dashboard:'Panel',nav_profiles:'Perfiles',nav_missions:'Misiones',nav_modes:'Modos',nav_rewards:'Premios',nav_settings:'Ajustes',nav_history:'Historial',nav_data:'Datos',parentSection:'Padres: {section}',summary:'{heroes} héroes activos • {missions} misiones activas • {sessions} sesiones guardadas',autoClose:'El modo para padres se cierra automáticamente después de cinco minutos de inactividad.',returnChild:'Volver al modo infantil',active:'Activo',save:'Guardar',profileSaved:'Perfil guardado.',addHero:'Agregar héroe',removeHero:'Quitar',participantLimit:'Hasta {count} héroes pueden participar en una batalla.',heroName:'Nombre del héroe',timerLabel:'Temporizador de misión',timerReset:'¡Nueva oportunidad! 5:00',timerExpired:'Parece que se les pasó la primera oportunidad, pero ahora el monstruo está distraído. Todavía pueden lograrlo — ¡inténtenlo otra vez!',timerExpiredAgain:'¡El monstruo sigue distraído! Tienen otros cinco minutos. ¡Sigan adelante!',missionAlarm:'¡Comienza una misión importante!',moreHeroes:'Agregar otro héroe',newHero:'Nuevo héroe',roomRanger:'Guardián del Cuarto',duplicate:'Duplicar',copySuffix:' Copia',missionUpdated:'Misión actualizada.',restoreFactory:'Restaurar misiones originales',restoreConfirm:'¿Restaurar las ocho misiones originales? Las misiones personalizadas se conservan.',familyReward:'Mensaje de premio familiar',saveReward:'Guardar mensaje de premio',rewardSaved:'Mensaje de premio guardado.',spokenSetting:'Instrucciones habladas de la misión',inspectSetting:'Requerir inspección final de padres',reduceMotion:'Reducir animación',interfaceLanguage:'Idioma de la interfaz',saveSettings:'Guardar ajustes',settingsSaved:'Ajustes guardados.',noBattles:'Todavía no hay batallas completadas.',battle:'Batalla',missionsWord:'misiones',inspected:'Inspeccionado',completed:'Completado',exportBackup:'Exportar respaldo JSON',importBackup:'Importar respaldo',validateImport:'Validar e importar',resetWarning:'El reinicio completo elimina los datos familiares locales de este navegador.',fullReset:'Reinicio completo…',chooseBackup:'Primero elige un respaldo JSON.',validBackup:'Respaldo válido: {heroes} héroes, {missions} misiones, {sessions} sesiones. ¿Reemplazar los datos locales actuales?',backupImported:'Respaldo importado.',importRejected:'Importación rechazada: {message}',reset1:'Primera confirmación: ¿eliminar todos los datos locales de Room Monster Battle?',reset2:'Segunda confirmación: esto no se puede deshacer sin un respaldo. ¿Continuar?',resetPhrase:'Escribe RESET ROOM MONSTER para terminar:',resetCancelled:'Reinicio cancelado.',
    quick:'Rescate Rápido',normal:'Batalla Normal',deep:'Limpieza Profunda',finder:'Buscador',sorter:'Clasificador',organizer:'Organizador',trashScout:'Explorador de Basura',toyCaptain:'Capitán de Juguetes',bedBuilder:'Constructor de Camas',finalInspector:'Inspector Final',closet:'Clóset',bookshelf:'Librero',floor:'Piso',toyZone:'Zona de Juguetes',beds:'Camas',wholeRoom:'Todo el Cuarto'
  }
};
let current='en';
export function setLanguage(lang){current=lang==='es'?'es':'en';document.documentElement.lang=current;}
export function getLanguage(){return current}
export function t(key,vars={}){let s=(dictionaries[current]&&dictionaries[current][key])??dictionaries.en[key]??key;return String(s).replace(/\{(\w+)\}/g,(_,k)=>vars[k]??'')}
const roleKeys={'Finder':'finder','Sorter':'sorter','Organizer':'organizer','Trash Scout':'trashScout','Toy Captain':'toyCaptain','Bed Builder':'bedBuilder','Final Inspector':'finalInspector'};
export function roleName(name){return t(roleKeys[name]||name)}
export function localized(record,field){if(!record)return'';const alt=field+'Es';return current==='es'?(record[alt]||record[field]||''):(record[field]||record[alt]||'')}
export function modeName(mode){if(!mode)return t('battle');if(mode.nameEs||mode.name)return localized(mode,'name');const key={quick:'quick',normal:'normal',deep:'deep'}[mode.id];return key?t(key):mode.id}
export function zoneName(zone){if(!zone)return'';return localized(zone,'name')}
